-- ─── Migration 007: Real-time signal storage ─────────────────────────────────
-- Rule-based signals generated by cron jobs from RSI, MACD, EMA crossovers,
-- and divergences. Stored with Realtime enabled for live UI updates.

CREATE TABLE IF NOT EXISTS public.signals (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at  timestamptz DEFAULT now() NOT NULL,
  asset       text NOT NULL,               -- 'BTC/USD', 'EUR/USD', 'AAPL'
  asset_name  text NOT NULL,               -- 'Bitcoin', 'Euro/Dollar', 'Apple'
  category    text NOT NULL CHECK (category IN ('crypto', 'forex', 'stocks', 'indices')),
  timeframe   text NOT NULL CHECK (timeframe IN ('15m', '1h', '4h', '1d')),
  signal_type text NOT NULL,               -- 'RSI_OVERSOLD', 'MACD_CROSS', etc.
  direction   text NOT NULL CHECK (direction IN ('BULLISH', 'BEARISH')),
  strength    smallint NOT NULL CHECK (strength BETWEEN 0 AND 100),
  price       numeric(20, 8),
  rsi         numeric(6, 2),
  ema20       numeric(20, 8),
  ema50       numeric(20, 8),
  details     jsonb DEFAULT '{}'::jsonb
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_signals_created_at
  ON public.signals (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signals_dedup
  ON public.signals (asset, timeframe, signal_type, direction, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signals_category
  ON public.signals (category, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signals_direction
  ON public.signals (direction, created_at DESC);

-- ─── Row Level Security ───────────────────────────────────────────────────────

ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read all signals
CREATE POLICY "signals_authenticated_read"
  ON public.signals FOR SELECT
  TO authenticated
  USING (true);

-- Service role has full access (used by cron job to insert)
CREATE POLICY "signals_service_role_all"
  ON public.signals FOR ALL
  TO service_role
  USING (true);

-- ─── Realtime ─────────────────────────────────────────────────────────────────

ALTER PUBLICATION supabase_realtime ADD TABLE public.signals;

-- ─── Auto-cleanup: delete signals older than 7 days ───────────────────────────
-- Keeps the table lean. Can be run manually or via a daily pg_cron job.
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- SELECT cron.schedule('cleanup-signals', '0 3 * * *',
--   $$DELETE FROM public.signals WHERE created_at < NOW() - INTERVAL '7 days'$$);
